# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
url:         "" # the base hostname & protocol for your site
baseurl:     "" # the subpath of your site, e.g. /blog
title:       Baurine's Blog
description: > # this means to ignore newlines until "links:"
  Work hard, Enjoy life.
signoff:     Baurine
img_url:     /assets/images
links:
  - name:         Blog
    url:          /
  - name:         GitHub
    url:          https://github.com/baurine
    external:     true
  # - name:         About
  #   url:          /about

# Build settings
markdown: kramdown
